/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package BoardService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the REP service. Represents a row in the &quot;HHL_PROJECT_REP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>BoardService.model.impl.REPModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>BoardService.model.impl.REPImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see REP
 * @generated
 */
@ProviderType
public interface REPModel extends BaseModel<REP> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rep model instance should use the {@link REP} interface instead.
	 */

	/**
	 * Returns the primary key of this rep.
	 *
	 * @return the primary key of this rep
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rep.
	 *
	 * @param primaryKey the primary key of this rep
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rno of this rep.
	 *
	 * @return the rno of this rep
	 */
	public long getRno();

	/**
	 * Sets the rno of this rep.
	 *
	 * @param rno the rno of this rep
	 */
	public void setRno(long rno);

	/**
	 * Returns the bno of this rep.
	 *
	 * @return the bno of this rep
	 */
	public long getBno();

	/**
	 * Sets the bno of this rep.
	 *
	 * @param bno the bno of this rep
	 */
	public void setBno(long bno);

	/**
	 * Returns the r writer of this rep.
	 *
	 * @return the r writer of this rep
	 */
	@AutoEscape
	public String getRWriter();

	/**
	 * Sets the r writer of this rep.
	 *
	 * @param rWriter the r writer of this rep
	 */
	public void setRWriter(String rWriter);

	/**
	 * Returns the r contents of this rep.
	 *
	 * @return the r contents of this rep
	 */
	@AutoEscape
	public String getRContents();

	/**
	 * Sets the r contents of this rep.
	 *
	 * @param rContents the r contents of this rep
	 */
	public void setRContents(String rContents);

	/**
	 * Returns the r reg date of this rep.
	 *
	 * @return the r reg date of this rep
	 */
	@AutoEscape
	public String getRRegDate();

	/**
	 * Sets the r reg date of this rep.
	 *
	 * @param rRegDate the r reg date of this rep
	 */
	public void setRRegDate(String rRegDate);

}