/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package BoardService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TBL service. Represents a row in the &quot;HHL_PROJECT_TBL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>BoardService.model.impl.TBLModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>BoardService.model.impl.TBLImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TBL
 * @generated
 */
@ProviderType
public interface TBLModel extends BaseModel<TBL> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tbl model instance should use the {@link TBL} interface instead.
	 */

	/**
	 * Returns the primary key of this tbl.
	 *
	 * @return the primary key of this tbl
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tbl.
	 *
	 * @param primaryKey the primary key of this tbl
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bno of this tbl.
	 *
	 * @return the bno of this tbl
	 */
	public long getBno();

	/**
	 * Sets the bno of this tbl.
	 *
	 * @param bno the bno of this tbl
	 */
	public void setBno(long bno);

	/**
	 * Returns the subject of this tbl.
	 *
	 * @return the subject of this tbl
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this tbl.
	 *
	 * @param subject the subject of this tbl
	 */
	public void setSubject(String subject);

	/**
	 * Returns the writer of this tbl.
	 *
	 * @return the writer of this tbl
	 */
	@AutoEscape
	public String getWriter();

	/**
	 * Sets the writer of this tbl.
	 *
	 * @param writer the writer of this tbl
	 */
	public void setWriter(String writer);

	/**
	 * Returns the contents of this tbl.
	 *
	 * @return the contents of this tbl
	 */
	@AutoEscape
	public String getContents();

	/**
	 * Sets the contents of this tbl.
	 *
	 * @param contents the contents of this tbl
	 */
	public void setContents(String contents);

	/**
	 * Returns the reg date of this tbl.
	 *
	 * @return the reg date of this tbl
	 */
	@AutoEscape
	public String getRegDate();

	/**
	 * Sets the reg date of this tbl.
	 *
	 * @param regDate the reg date of this tbl
	 */
	public void setRegDate(String regDate);

	/**
	 * Returns the hit of this tbl.
	 *
	 * @return the hit of this tbl
	 */
	public int getHit();

	/**
	 * Sets the hit of this tbl.
	 *
	 * @param hit the hit of this tbl
	 */
	public void setHit(int hit);

	/**
	 * Returns the subject_id of this tbl.
	 *
	 * @return the subject_id of this tbl
	 */
	public int getSubject_id();

	/**
	 * Sets the subject_id of this tbl.
	 *
	 * @param subject_id the subject_id of this tbl
	 */
	public void setSubject_id(int subject_id);

}